[meta]
name = "TF2Attributes"
description = "Set, get and modify TF2 entity attributes"
author = "FlaminSarge"

[source]
type = "git"
repository = "https://github.com/JoinedSenses/SourceMod-IncludeLibrary.git"
patterns = [
	"include/tf2attributes.inc"
]
